/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Demo1RouteImport } from './routes/demo-1'
import { Route as Demo2RouteImport } from './routes/demo-2'
import { Route as Demo1IndexRouteImport } from './routes/demo-1.index'
import { Route as Demo1AboutRouteImport } from './routes/demo-1.about'
import { Route as Demo1ContactRouteImport } from './routes/demo-1.contact'
import { Route as Demo1ServicesRouteImport } from './routes/demo-1.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo1Route = Demo1RouteImport.update({
  id: '/demo-1',
  path: '/demo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo2Route = Demo2RouteImport.update({
  id: '/demo-2',
  path: '/demo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo1IndexRoute = Demo1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Demo1Route,
} as any)
const Demo1AboutRoute = Demo1AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Demo1Route,
} as any)
const Demo1ContactRoute = Demo1ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => Demo1Route,
} as any)
const Demo1ServicesRoute = Demo1ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => Demo1Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-1': typeof Demo1RouteWithChildren
  '/demo-2': typeof Demo2Route
  '/demo-1/about': typeof Demo1AboutRoute
  '/demo-1/contact': typeof Demo1ContactRoute
  '/demo-1/services': typeof Demo1ServicesRoute
  '/demo-1/': typeof Demo1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-2': typeof Demo2Route
  '/demo-1/about': typeof Demo1AboutRoute
  '/demo-1/contact': typeof Demo1ContactRoute
  '/demo-1/services': typeof Demo1ServicesRoute
  '/demo-1': typeof Demo1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-1': typeof Demo1RouteWithChildren
  '/demo-2': typeof Demo2Route
  '/demo-1/about': typeof Demo1AboutRoute
  '/demo-1/contact': typeof Demo1ContactRoute
  '/demo-1/services': typeof Demo1ServicesRoute
  '/demo-1/': typeof Demo1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo-1'
    | '/demo-2'
    | '/demo-1/about'
    | '/demo-1/contact'
    | '/demo-1/services'
    | '/demo-1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-2'
    | '/demo-1/about'
    | '/demo-1/contact'
    | '/demo-1/services'
    | '/demo-1'
  id:
    | '__root__'
    | '/'
    | '/demo-1'
    | '/demo-2'
    | '/demo-1/about'
    | '/demo-1/contact'
    | '/demo-1/services'
    | '/demo-1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Demo1Route: typeof Demo1RouteWithChildren
  Demo2Route: typeof Demo2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-1': {
      id: '/demo-1'
      path: '/demo-1'
      fullPath: '/demo-1'
      preLoaderRoute: typeof Demo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-2': {
      id: '/demo-2'
      path: '/demo-2'
      fullPath: '/demo-2'
      preLoaderRoute: typeof Demo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-1/': {
      id: '/demo-1/'
      path: '/'
      fullPath: '/demo-1/'
      preLoaderRoute: typeof Demo1IndexRouteImport
      parentRoute: typeof Demo1Route
    }
    '/demo-1/about': {
      id: '/demo-1/about'
      path: '/about'
      fullPath: '/demo-1/about'
      preLoaderRoute: typeof Demo1AboutRouteImport
      parentRoute: typeof Demo1Route
    }
    '/demo-1/contact': {
      id: '/demo-1/contact'
      path: '/contact'
      fullPath: '/demo-1/contact'
      preLoaderRoute: typeof Demo1ContactRouteImport
      parentRoute: typeof Demo1Route
    }
    '/demo-1/services': {
      id: '/demo-1/services'
      path: '/services'
      fullPath: '/demo-1/services'
      preLoaderRoute: typeof Demo1ServicesRouteImport
      parentRoute: typeof Demo1Route
    }
  }
}

interface Demo1RouteChildren {
  Demo1AboutRoute: typeof Demo1AboutRoute
  Demo1ContactRoute: typeof Demo1ContactRoute
  Demo1ServicesRoute: typeof Demo1ServicesRoute
  Demo1IndexRoute: typeof Demo1IndexRoute
}

const Demo1RouteChildren: Demo1RouteChildren = {
  Demo1AboutRoute: Demo1AboutRoute,
  Demo1ContactRoute: Demo1ContactRoute,
  Demo1ServicesRoute: Demo1ServicesRoute,
  Demo1IndexRoute: Demo1IndexRoute,
}

const Demo1RouteWithChildren = Demo1Route._addFileChildren(Demo1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Demo1Route: Demo1RouteWithChildren,
  Demo2Route: Demo2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
